apiVersion: apps/v1
kind: Deployment
metadata:
  name: k9s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k9s
  template:
    metadata:
      labels:
        app: k9s
    spec:
      containers:
        - name: k9s
          image: derailed/k9s:latest
          command: ["k9s"]